### ISSUE TITLE
Overhead in constr_eq.v

### ISSUE THREAD

**Issue by mrhaandi** [mit-plv/engine-bench#3]
https://github.com/mit-plv/engine-bench/blob/f5c7ad8c8979f231e1c5ad0f927cc6577f59245b/coq/PerformanceDemos/constr_eq.v#L22

What about the following tail-recursive variants of `biga`, `bigb`?

```coq
(* tail-recursive biga, bigb *)
Fixpoint biga' (n : nat) (f : Prop -> Prop)
:= match n with
   | 0 => f True
   | S n => biga' n (fun x => forall a : Prop, f (a -> x)) 
   end.
Fixpoint bigb' (n : nat) (f : Prop -> Prop)
:= match n with
   | 0 => f True
   | S n => bigb' n (fun x => forall b : Prop, f (b -> x)) 
   end.
```
On my system: 
original: `(real: 7.15, user: 6.75, sys: 0.35, mem: 2544640 ko)`
tail-recursive: `(real: 0.13, user: 0.08, sys: 0.01, mem: 173364 ko)`

**Comment by JasonGross** [comment]
This is very nice, thanks! Could you submit a PR?

**Comment by mrhaandi** [comment]
> This is very nice, thanks! Could you submit a PR?

Done https://github.com/mit-plv/engine-bench/pull/4. I hope memory requirements keep low.
